version: 0.2

phases:
  test:
    commands:
      - echo "Tests started"
      - mvn test
      - echo "Test OK"
  build:
    commands:
      - echo "Build started"
      - mvn clean install -DskipTests
  post_build:
    commands:
      - echo "Pipeline success"
      - mv target/*.jar blue-bank.jar

artifacts:
  files:
    - blue-bank.jar

cache:
  paths:
    - '/root/.m2/**/*'
